# ==============================================================================
#                                 PROJECT
# ==============================================================================
[project]
name = "your-project-name"
version = "0.1.0"
description = "A short description of your project."
requires-python = ">=3.9"
# Add your project's core dependencies here.
dependencies = []
