# ==============================================================================
#                                 PROJECT
# ==============================================================================
[project]
name = "your-project-name"
version = "0.1.0"
description = "A short description of your project."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development",
]
keywords = ["keyword1", "keyword2"]
# Add your project's dependencies here.
dependencies = []

[project.urls]
Homepage = "https://github.com/your-username/your-project-name"
Documentation = "https://github.com/your-username/your-project-name#readme"
Issues = "https://github.com/your-username/your-project-name/issues"
Source = "https://github.com/your-username/your-project-name"

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
]

# ==============================================================================
#                                  TOOLS
# ==============================================================================
[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "C4", "SIM", "A"]
ignore = ["E501", "B905"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
