[project]
name = "project-cleanup"
version = "0.1.0"
description = "A script to clean temporary files and directories from the monorepo."
authors = [{ name = "Gemini", email = "gemini@google.com" }]
dependencies = []