[project]
name = "project-cleanup"
version = "0.1.0"
description = "A script to clean temporary files and directories from the monorepo."
authors = [{ name = "dunamismax", email = "dunamismax@google.com" }]
dependencies = [
    "ruff==0.12.2"
]