[project]
name = "project-setup"
version = "0.1.0"
description = "A script to set up all projects in the monorepo."
authors = [{ name = "dunamismax", email = "dunamismax@google.com" }]
dependencies = [
    "ruff==0.12.2"
]
